### ISSUE TITLE
[ERROR] [1733483733.178024539] [rcl]: Failed to parse global arguments

### ISSUE THREAD

**Issue by DONJAGA** [arshadlab/multi_robot_arm#1]
Script Execution Error for `python ex_pose_goal.py --ros-args -r __ns:=/arm1 -p position:=[0.5, 0.4,0.2]` 
```
[ERROR] [1733483733.178024539] [rcl]: Failed to parse global arguments
Traceback (most recent call last):
  File "/home/don/robot_ws/src/pymoveit2/examples/ex_pose_goal.py", line 153, in <module>
    main()
  File "/home/don/robot_ws/src/pymoveit2/examples/ex_pose_goal.py", line 25, in main
    rclpy.init()
  File "/home/don/ros2_humble/install/rclpy/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 88, in init
    context.init(args, domain_id=domain_id)
  File "/home/don/ros2_humble/install/rclpy/local/lib/python3.10/dist-packages/rclpy/context.py", line 72, in init
    self.__context = _rclpy.Context(
rclpy._rclpy_pybind11.RCLError: failed to initialize rcl: Couldn't parse parameter override rule: '-p position:=[0.5,'. Error: Error parsing an event, at /home/don/ros2_humble/src/ros2/rcl/rcl_yaml_param_parser/src/parse.c:922, at /home/don/ros2_humble/src/ros2/rcl/rcl/src/rcl/arguments.c:343

```

**Comment by DONJAGA** [comment]
The error is due to the incorrect formatting of the command-line arguments, specifically the way the position parameter is passed. According to the ex_pose_goal.py script, the expected format for the -p arguments is a properly quoted YAML-compatible list (e.g., "[0.5, 0.4, 0.2]"). 
Therefore the correct executable command should be : 
`$ python3 ex_pose_goal.py --ros-args -r __ns:=/arm1 -p position:="[0.5, 0.4, 0.2]"
`
